/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: vulkan.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "vulkan.pb-c.h"
void   pinput_transaction__init
                     (PInputTransaction         *message)
{
  static const PInputTransaction init_value = PINPUT_TRANSACTION__INIT;
  *message = init_value;
}
size_t pinput_transaction__get_packed_size
                     (const PInputTransaction *message)
{
  assert(message->base.descriptor == &pinput_transaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pinput_transaction__pack
                     (const PInputTransaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pinput_transaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pinput_transaction__pack_to_buffer
                     (const PInputTransaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pinput_transaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PInputTransaction *
       pinput_transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PInputTransaction *)
     protobuf_c_message_unpack (&pinput_transaction__descriptor,
                                allocator, len, data);
}
void   pinput_transaction__free_unpacked
                     (PInputTransaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pinput_transaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   poutput_transaction__init
                     (POutputTransaction         *message)
{
  static const POutputTransaction init_value = POUTPUT_TRANSACTION__INIT;
  *message = init_value;
}
size_t poutput_transaction__get_packed_size
                     (const POutputTransaction *message)
{
  assert(message->base.descriptor == &poutput_transaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t poutput_transaction__pack
                     (const POutputTransaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &poutput_transaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t poutput_transaction__pack_to_buffer
                     (const POutputTransaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &poutput_transaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
POutputTransaction *
       poutput_transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (POutputTransaction *)
     protobuf_c_message_unpack (&poutput_transaction__descriptor,
                                allocator, len, data);
}
void   poutput_transaction__free_unpacked
                     (POutputTransaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &poutput_transaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ptransaction__init
                     (PTransaction         *message)
{
  static const PTransaction init_value = PTRANSACTION__INIT;
  *message = init_value;
}
size_t ptransaction__get_packed_size
                     (const PTransaction *message)
{
  assert(message->base.descriptor == &ptransaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ptransaction__pack
                     (const PTransaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ptransaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ptransaction__pack_to_buffer
                     (const PTransaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ptransaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PTransaction *
       ptransaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PTransaction *)
     protobuf_c_message_unpack (&ptransaction__descriptor,
                                allocator, len, data);
}
void   ptransaction__free_unpacked
                     (PTransaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ptransaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   punspent_output_transaction__init
                     (PUnspentOutputTransaction         *message)
{
  static const PUnspentOutputTransaction init_value = PUNSPENT_OUTPUT_TRANSACTION__INIT;
  *message = init_value;
}
size_t punspent_output_transaction__get_packed_size
                     (const PUnspentOutputTransaction *message)
{
  assert(message->base.descriptor == &punspent_output_transaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t punspent_output_transaction__pack
                     (const PUnspentOutputTransaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &punspent_output_transaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t punspent_output_transaction__pack_to_buffer
                     (const PUnspentOutputTransaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &punspent_output_transaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PUnspentOutputTransaction *
       punspent_output_transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PUnspentOutputTransaction *)
     protobuf_c_message_unpack (&punspent_output_transaction__descriptor,
                                allocator, len, data);
}
void   punspent_output_transaction__free_unpacked
                     (PUnspentOutputTransaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &punspent_output_transaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   punspent_transaction__init
                     (PUnspentTransaction         *message)
{
  static const PUnspentTransaction init_value = PUNSPENT_TRANSACTION__INIT;
  *message = init_value;
}
size_t punspent_transaction__get_packed_size
                     (const PUnspentTransaction *message)
{
  assert(message->base.descriptor == &punspent_transaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t punspent_transaction__pack
                     (const PUnspentTransaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &punspent_transaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t punspent_transaction__pack_to_buffer
                     (const PUnspentTransaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &punspent_transaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PUnspentTransaction *
       punspent_transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PUnspentTransaction *)
     protobuf_c_message_unpack (&punspent_transaction__descriptor,
                                allocator, len, data);
}
void   punspent_transaction__free_unpacked
                     (PUnspentTransaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &punspent_transaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pblock__init
                     (PBlock         *message)
{
  static const PBlock init_value = PBLOCK__INIT;
  *message = init_value;
}
size_t pblock__get_packed_size
                     (const PBlock *message)
{
  assert(message->base.descriptor == &pblock__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pblock__pack
                     (const PBlock *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pblock__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pblock__pack_to_buffer
                     (const PBlock *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pblock__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PBlock *
       pblock__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PBlock *)
     protobuf_c_message_unpack (&pblock__descriptor,
                                allocator, len, data);
}
void   pblock__free_unpacked
                     (PBlock *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pblock__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pwallet__init
                     (PWallet         *message)
{
  static const PWallet init_value = PWALLET__INIT;
  *message = init_value;
}
size_t pwallet__get_packed_size
                     (const PWallet *message)
{
  assert(message->base.descriptor == &pwallet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pwallet__pack
                     (const PWallet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pwallet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pwallet__pack_to_buffer
                     (const PWallet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pwallet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PWallet *
       pwallet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PWallet *)
     protobuf_c_message_unpack (&pwallet__descriptor,
                                allocator, len, data);
}
void   pwallet__free_unpacked
                     (PWallet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pwallet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pempty__init
                     (PEmpty         *message)
{
  static const PEmpty init_value = PEMPTY__INIT;
  *message = init_value;
}
size_t pempty__get_packed_size
                     (const PEmpty *message)
{
  assert(message->base.descriptor == &pempty__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pempty__pack
                     (const PEmpty *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pempty__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pempty__pack_to_buffer
                     (const PEmpty *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pempty__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PEmpty *
       pempty__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PEmpty *)
     protobuf_c_message_unpack (&pempty__descriptor,
                                allocator, len, data);
}
void   pempty__free_unpacked
                     (PEmpty *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pempty__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ppacket__init
                     (PPacket         *message)
{
  static const PPacket init_value = PPACKET__INIT;
  *message = init_value;
}
size_t ppacket__get_packed_size
                     (const PPacket *message)
{
  assert(message->base.descriptor == &ppacket__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ppacket__pack
                     (const PPacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ppacket__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ppacket__pack_to_buffer
                     (const PPacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ppacket__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PPacket *
       ppacket__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PPacket *)
     protobuf_c_message_unpack (&ppacket__descriptor,
                                allocator, len, data);
}
void   ppacket__free_unpacked
                     (PPacket *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ppacket__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mincoming_block__init
                     (MIncomingBlock         *message)
{
  static const MIncomingBlock init_value = MINCOMING_BLOCK__INIT;
  *message = init_value;
}
size_t mincoming_block__get_packed_size
                     (const MIncomingBlock *message)
{
  assert(message->base.descriptor == &mincoming_block__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mincoming_block__pack
                     (const MIncomingBlock *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mincoming_block__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mincoming_block__pack_to_buffer
                     (const MIncomingBlock *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mincoming_block__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MIncomingBlock *
       mincoming_block__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MIncomingBlock *)
     protobuf_c_message_unpack (&mincoming_block__descriptor,
                                allocator, len, data);
}
void   mincoming_block__free_unpacked
                     (MIncomingBlock *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mincoming_block__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mincoming_transaction__init
                     (MIncomingTransaction         *message)
{
  static const MIncomingTransaction init_value = MINCOMING_TRANSACTION__INIT;
  *message = init_value;
}
size_t mincoming_transaction__get_packed_size
                     (const MIncomingTransaction *message)
{
  assert(message->base.descriptor == &mincoming_transaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mincoming_transaction__pack
                     (const MIncomingTransaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mincoming_transaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mincoming_transaction__pack_to_buffer
                     (const MIncomingTransaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mincoming_transaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MIncomingTransaction *
       mincoming_transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MIncomingTransaction *)
     protobuf_c_message_unpack (&mincoming_transaction__descriptor,
                                allocator, len, data);
}
void   mincoming_transaction__free_unpacked
                     (MIncomingTransaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mincoming_transaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mget_block_height_request__init
                     (MGetBlockHeightRequest         *message)
{
  static const MGetBlockHeightRequest init_value = MGET_BLOCK_HEIGHT_REQUEST__INIT;
  *message = init_value;
}
size_t mget_block_height_request__get_packed_size
                     (const MGetBlockHeightRequest *message)
{
  assert(message->base.descriptor == &mget_block_height_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mget_block_height_request__pack
                     (const MGetBlockHeightRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mget_block_height_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mget_block_height_request__pack_to_buffer
                     (const MGetBlockHeightRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mget_block_height_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MGetBlockHeightRequest *
       mget_block_height_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MGetBlockHeightRequest *)
     protobuf_c_message_unpack (&mget_block_height_request__descriptor,
                                allocator, len, data);
}
void   mget_block_height_request__free_unpacked
                     (MGetBlockHeightRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mget_block_height_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mget_block_height_response__init
                     (MGetBlockHeightResponse         *message)
{
  static const MGetBlockHeightResponse init_value = MGET_BLOCK_HEIGHT_RESPONSE__INIT;
  *message = init_value;
}
size_t mget_block_height_response__get_packed_size
                     (const MGetBlockHeightResponse *message)
{
  assert(message->base.descriptor == &mget_block_height_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mget_block_height_response__pack
                     (const MGetBlockHeightResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mget_block_height_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mget_block_height_response__pack_to_buffer
                     (const MGetBlockHeightResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mget_block_height_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MGetBlockHeightResponse *
       mget_block_height_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MGetBlockHeightResponse *)
     protobuf_c_message_unpack (&mget_block_height_response__descriptor,
                                allocator, len, data);
}
void   mget_block_height_response__free_unpacked
                     (MGetBlockHeightResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mget_block_height_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mget_block_request__init
                     (MGetBlockRequest         *message)
{
  static const MGetBlockRequest init_value = MGET_BLOCK_REQUEST__INIT;
  *message = init_value;
}
size_t mget_block_request__get_packed_size
                     (const MGetBlockRequest *message)
{
  assert(message->base.descriptor == &mget_block_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mget_block_request__pack
                     (const MGetBlockRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mget_block_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mget_block_request__pack_to_buffer
                     (const MGetBlockRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mget_block_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MGetBlockRequest *
       mget_block_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MGetBlockRequest *)
     protobuf_c_message_unpack (&mget_block_request__descriptor,
                                allocator, len, data);
}
void   mget_block_request__free_unpacked
                     (MGetBlockRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mget_block_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mget_block_response__init
                     (MGetBlockResponse         *message)
{
  static const MGetBlockResponse init_value = MGET_BLOCK_RESPONSE__INIT;
  *message = init_value;
}
size_t mget_block_response__get_packed_size
                     (const MGetBlockResponse *message)
{
  assert(message->base.descriptor == &mget_block_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mget_block_response__pack
                     (const MGetBlockResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mget_block_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mget_block_response__pack_to_buffer
                     (const MGetBlockResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mget_block_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MGetBlockResponse *
       mget_block_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MGetBlockResponse *)
     protobuf_c_message_unpack (&mget_block_response__descriptor,
                                allocator, len, data);
}
void   mget_block_response__free_unpacked
                     (MGetBlockResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mget_block_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mget_num_transactions_request__init
                     (MGetNumTransactionsRequest         *message)
{
  static const MGetNumTransactionsRequest init_value = MGET_NUM_TRANSACTIONS_REQUEST__INIT;
  *message = init_value;
}
size_t mget_num_transactions_request__get_packed_size
                     (const MGetNumTransactionsRequest *message)
{
  assert(message->base.descriptor == &mget_num_transactions_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mget_num_transactions_request__pack
                     (const MGetNumTransactionsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mget_num_transactions_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mget_num_transactions_request__pack_to_buffer
                     (const MGetNumTransactionsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mget_num_transactions_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MGetNumTransactionsRequest *
       mget_num_transactions_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MGetNumTransactionsRequest *)
     protobuf_c_message_unpack (&mget_num_transactions_request__descriptor,
                                allocator, len, data);
}
void   mget_num_transactions_request__free_unpacked
                     (MGetNumTransactionsRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mget_num_transactions_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mget_num_transactions_response__init
                     (MGetNumTransactionsResponse         *message)
{
  static const MGetNumTransactionsResponse init_value = MGET_NUM_TRANSACTIONS_RESPONSE__INIT;
  *message = init_value;
}
size_t mget_num_transactions_response__get_packed_size
                     (const MGetNumTransactionsResponse *message)
{
  assert(message->base.descriptor == &mget_num_transactions_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mget_num_transactions_response__pack
                     (const MGetNumTransactionsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mget_num_transactions_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mget_num_transactions_response__pack_to_buffer
                     (const MGetNumTransactionsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mget_num_transactions_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MGetNumTransactionsResponse *
       mget_num_transactions_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MGetNumTransactionsResponse *)
     protobuf_c_message_unpack (&mget_num_transactions_response__descriptor,
                                allocator, len, data);
}
void   mget_num_transactions_response__free_unpacked
                     (MGetNumTransactionsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mget_num_transactions_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mget_all_transaction_ids_request__init
                     (MGetAllTransactionIdsRequest         *message)
{
  static const MGetAllTransactionIdsRequest init_value = MGET_ALL_TRANSACTION_IDS_REQUEST__INIT;
  *message = init_value;
}
size_t mget_all_transaction_ids_request__get_packed_size
                     (const MGetAllTransactionIdsRequest *message)
{
  assert(message->base.descriptor == &mget_all_transaction_ids_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mget_all_transaction_ids_request__pack
                     (const MGetAllTransactionIdsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mget_all_transaction_ids_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mget_all_transaction_ids_request__pack_to_buffer
                     (const MGetAllTransactionIdsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mget_all_transaction_ids_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MGetAllTransactionIdsRequest *
       mget_all_transaction_ids_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MGetAllTransactionIdsRequest *)
     protobuf_c_message_unpack (&mget_all_transaction_ids_request__descriptor,
                                allocator, len, data);
}
void   mget_all_transaction_ids_request__free_unpacked
                     (MGetAllTransactionIdsRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mget_all_transaction_ids_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mget_all_transaction_ids_response__init
                     (MGetAllTransactionIdsResponse         *message)
{
  static const MGetAllTransactionIdsResponse init_value = MGET_ALL_TRANSACTION_IDS_RESPONSE__INIT;
  *message = init_value;
}
size_t mget_all_transaction_ids_response__get_packed_size
                     (const MGetAllTransactionIdsResponse *message)
{
  assert(message->base.descriptor == &mget_all_transaction_ids_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mget_all_transaction_ids_response__pack
                     (const MGetAllTransactionIdsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mget_all_transaction_ids_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mget_all_transaction_ids_response__pack_to_buffer
                     (const MGetAllTransactionIdsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mget_all_transaction_ids_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MGetAllTransactionIdsResponse *
       mget_all_transaction_ids_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MGetAllTransactionIdsResponse *)
     protobuf_c_message_unpack (&mget_all_transaction_ids_response__descriptor,
                                allocator, len, data);
}
void   mget_all_transaction_ids_response__free_unpacked
                     (MGetAllTransactionIdsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mget_all_transaction_ids_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mget_transaction_request__init
                     (MGetTransactionRequest         *message)
{
  static const MGetTransactionRequest init_value = MGET_TRANSACTION_REQUEST__INIT;
  *message = init_value;
}
size_t mget_transaction_request__get_packed_size
                     (const MGetTransactionRequest *message)
{
  assert(message->base.descriptor == &mget_transaction_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mget_transaction_request__pack
                     (const MGetTransactionRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mget_transaction_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mget_transaction_request__pack_to_buffer
                     (const MGetTransactionRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mget_transaction_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MGetTransactionRequest *
       mget_transaction_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MGetTransactionRequest *)
     protobuf_c_message_unpack (&mget_transaction_request__descriptor,
                                allocator, len, data);
}
void   mget_transaction_request__free_unpacked
                     (MGetTransactionRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mget_transaction_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mget_transaction_response__init
                     (MGetTransactionResponse         *message)
{
  static const MGetTransactionResponse init_value = MGET_TRANSACTION_RESPONSE__INIT;
  *message = init_value;
}
size_t mget_transaction_response__get_packed_size
                     (const MGetTransactionResponse *message)
{
  assert(message->base.descriptor == &mget_transaction_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mget_transaction_response__pack
                     (const MGetTransactionResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mget_transaction_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mget_transaction_response__pack_to_buffer
                     (const MGetTransactionResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mget_transaction_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MGetTransactionResponse *
       mget_transaction_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MGetTransactionResponse *)
     protobuf_c_message_unpack (&mget_transaction_response__descriptor,
                                allocator, len, data);
}
void   mget_transaction_response__free_unpacked
                     (MGetTransactionResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mget_transaction_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pinput_transaction__field_descriptors[4] =
{
  {
    "transaction",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PInputTransaction, transaction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "txout_index",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PInputTransaction, txout_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PInputTransaction, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_key",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PInputTransaction, public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pinput_transaction__field_indices_by_name[] = {
  3,   /* field[3] = public_key */
  2,   /* field[2] = signature */
  0,   /* field[0] = transaction */
  1,   /* field[1] = txout_index */
};
static const ProtobufCIntRange pinput_transaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor pinput_transaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PInputTransaction",
  "PInputTransaction",
  "PInputTransaction",
  "",
  sizeof(PInputTransaction),
  4,
  pinput_transaction__field_descriptors,
  pinput_transaction__field_indices_by_name,
  1,  pinput_transaction__number_ranges,
  (ProtobufCMessageInit) pinput_transaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor poutput_transaction__field_descriptors[2] =
{
  {
    "amount",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(POutputTransaction, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(POutputTransaction, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned poutput_transaction__field_indices_by_name[] = {
  1,   /* field[1] = address */
  0,   /* field[0] = amount */
};
static const ProtobufCIntRange poutput_transaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor poutput_transaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "POutputTransaction",
  "POutputTransaction",
  "POutputTransaction",
  "",
  sizeof(POutputTransaction),
  2,
  poutput_transaction__field_descriptors,
  poutput_transaction__field_indices_by_name,
  1,  poutput_transaction__number_ranges,
  (ProtobufCMessageInit) poutput_transaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ptransaction__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PTransaction, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "txins",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PTransaction, n_txins),
    offsetof(PTransaction, txins),
    &pinput_transaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "txouts",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PTransaction, n_txouts),
    offsetof(PTransaction, txouts),
    &poutput_transaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ptransaction__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = txins */
  2,   /* field[2] = txouts */
};
static const ProtobufCIntRange ptransaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ptransaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PTransaction",
  "PTransaction",
  "PTransaction",
  "",
  sizeof(PTransaction),
  3,
  ptransaction__field_descriptors,
  ptransaction__field_indices_by_name,
  1,  ptransaction__number_ranges,
  (ProtobufCMessageInit) ptransaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor punspent_output_transaction__field_descriptors[3] =
{
  {
    "amount",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PUnspentOutputTransaction, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PUnspentOutputTransaction, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spent",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(PUnspentOutputTransaction, spent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned punspent_output_transaction__field_indices_by_name[] = {
  1,   /* field[1] = address */
  0,   /* field[0] = amount */
  2,   /* field[2] = spent */
};
static const ProtobufCIntRange punspent_output_transaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor punspent_output_transaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PUnspentOutputTransaction",
  "PUnspentOutputTransaction",
  "PUnspentOutputTransaction",
  "",
  sizeof(PUnspentOutputTransaction),
  3,
  punspent_output_transaction__field_descriptors,
  punspent_output_transaction__field_indices_by_name,
  1,  punspent_output_transaction__number_ranges,
  (ProtobufCMessageInit) punspent_output_transaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor punspent_transaction__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PUnspentTransaction, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "coinbase",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(PUnspentTransaction, coinbase),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unspent_txouts",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PUnspentTransaction, n_unspent_txouts),
    offsetof(PUnspentTransaction, unspent_txouts),
    &punspent_output_transaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned punspent_transaction__field_indices_by_name[] = {
  1,   /* field[1] = coinbase */
  0,   /* field[0] = id */
  2,   /* field[2] = unspent_txouts */
};
static const ProtobufCIntRange punspent_transaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor punspent_transaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PUnspentTransaction",
  "PUnspentTransaction",
  "PUnspentTransaction",
  "",
  sizeof(PUnspentTransaction),
  3,
  punspent_transaction__field_descriptors,
  punspent_transaction__field_indices_by_name,
  1,  punspent_transaction__number_ranges,
  (ProtobufCMessageInit) punspent_transaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pblock__field_descriptors[8] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PBlock, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bits",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PBlock, bits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "previous_hash",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PBlock, previous_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PBlock, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PBlock, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PBlock, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "merkle_root",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PBlock, merkle_root),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transactions",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PBlock, n_transactions),
    offsetof(PBlock, transactions),
    &ptransaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pblock__field_indices_by_name[] = {
  1,   /* field[1] = bits */
  3,   /* field[3] = hash */
  6,   /* field[6] = merkle_root */
  5,   /* field[5] = nonce */
  2,   /* field[2] = previous_hash */
  4,   /* field[4] = timestamp */
  7,   /* field[7] = transactions */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange pblock__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor pblock__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PBlock",
  "PBlock",
  "PBlock",
  "",
  sizeof(PBlock),
  8,
  pblock__field_descriptors,
  pblock__field_indices_by_name,
  1,  pblock__number_ranges,
  (ProtobufCMessageInit) pblock__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pwallet__field_descriptors[4] =
{
  {
    "secret_key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PWallet, secret_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PWallet, public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PWallet, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "balance",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PWallet, balance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pwallet__field_indices_by_name[] = {
  2,   /* field[2] = address */
  3,   /* field[3] = balance */
  1,   /* field[1] = public_key */
  0,   /* field[0] = secret_key */
};
static const ProtobufCIntRange pwallet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor pwallet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PWallet",
  "PWallet",
  "PWallet",
  "",
  sizeof(PWallet),
  4,
  pwallet__field_descriptors,
  pwallet__field_indices_by_name,
  1,  pwallet__number_ranges,
  (ProtobufCMessageInit) pwallet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define pempty__field_descriptors NULL
#define pempty__field_indices_by_name NULL
#define pempty__number_ranges NULL
const ProtobufCMessageDescriptor pempty__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PEmpty",
  "PEmpty",
  "PEmpty",
  "",
  sizeof(PEmpty),
  0,
  pempty__field_descriptors,
  pempty__field_indices_by_name,
  0,  pempty__number_ranges,
  (ProtobufCMessageInit) pempty__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ppacket__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PPacket, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_size",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PPacket, message_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PPacket, message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ppacket__field_indices_by_name[] = {
  0,   /* field[0] = id */
  2,   /* field[2] = message */
  1,   /* field[1] = message_size */
};
static const ProtobufCIntRange ppacket__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ppacket__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PPacket",
  "PPacket",
  "PPacket",
  "",
  sizeof(PPacket),
  3,
  ppacket__field_descriptors,
  ppacket__field_indices_by_name,
  1,  ppacket__number_ranges,
  (ProtobufCMessageInit) ppacket__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mincoming_block__field_descriptors[1] =
{
  {
    "block",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MIncomingBlock, block),
    &pblock__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mincoming_block__field_indices_by_name[] = {
  0,   /* field[0] = block */
};
static const ProtobufCIntRange mincoming_block__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mincoming_block__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MIncomingBlock",
  "MIncomingBlock",
  "MIncomingBlock",
  "",
  sizeof(MIncomingBlock),
  1,
  mincoming_block__field_descriptors,
  mincoming_block__field_indices_by_name,
  1,  mincoming_block__number_ranges,
  (ProtobufCMessageInit) mincoming_block__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mincoming_transaction__field_descriptors[1] =
{
  {
    "transaction",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MIncomingTransaction, transaction),
    &ptransaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mincoming_transaction__field_indices_by_name[] = {
  0,   /* field[0] = transaction */
};
static const ProtobufCIntRange mincoming_transaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mincoming_transaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MIncomingTransaction",
  "MIncomingTransaction",
  "MIncomingTransaction",
  "",
  sizeof(MIncomingTransaction),
  1,
  mincoming_transaction__field_descriptors,
  mincoming_transaction__field_indices_by_name,
  1,  mincoming_transaction__number_ranges,
  (ProtobufCMessageInit) mincoming_transaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define mget_block_height_request__field_descriptors NULL
#define mget_block_height_request__field_indices_by_name NULL
#define mget_block_height_request__number_ranges NULL
const ProtobufCMessageDescriptor mget_block_height_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MGetBlockHeightRequest",
  "MGetBlockHeightRequest",
  "MGetBlockHeightRequest",
  "",
  sizeof(MGetBlockHeightRequest),
  0,
  mget_block_height_request__field_descriptors,
  mget_block_height_request__field_indices_by_name,
  0,  mget_block_height_request__number_ranges,
  (ProtobufCMessageInit) mget_block_height_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mget_block_height_response__field_descriptors[2] =
{
  {
    "height",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MGetBlockHeightResponse, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MGetBlockHeightResponse, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mget_block_height_response__field_indices_by_name[] = {
  1,   /* field[1] = hash */
  0,   /* field[0] = height */
};
static const ProtobufCIntRange mget_block_height_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mget_block_height_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MGetBlockHeightResponse",
  "MGetBlockHeightResponse",
  "MGetBlockHeightResponse",
  "",
  sizeof(MGetBlockHeightResponse),
  2,
  mget_block_height_response__field_descriptors,
  mget_block_height_response__field_indices_by_name,
  1,  mget_block_height_response__number_ranges,
  (ProtobufCMessageInit) mget_block_height_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mget_block_request__field_descriptors[2] =
{
  {
    "height",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(MGetBlockRequest, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MGetBlockRequest, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mget_block_request__field_indices_by_name[] = {
  1,   /* field[1] = hash */
  0,   /* field[0] = height */
};
static const ProtobufCIntRange mget_block_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mget_block_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MGetBlockRequest",
  "MGetBlockRequest",
  "MGetBlockRequest",
  "",
  sizeof(MGetBlockRequest),
  2,
  mget_block_request__field_descriptors,
  mget_block_request__field_indices_by_name,
  1,  mget_block_request__number_ranges,
  (ProtobufCMessageInit) mget_block_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mget_block_response__field_descriptors[2] =
{
  {
    "height",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(MGetBlockResponse, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MGetBlockResponse, block),
    &pblock__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mget_block_response__field_indices_by_name[] = {
  1,   /* field[1] = block */
  0,   /* field[0] = height */
};
static const ProtobufCIntRange mget_block_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mget_block_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MGetBlockResponse",
  "MGetBlockResponse",
  "MGetBlockResponse",
  "",
  sizeof(MGetBlockResponse),
  2,
  mget_block_response__field_descriptors,
  mget_block_response__field_indices_by_name,
  1,  mget_block_response__number_ranges,
  (ProtobufCMessageInit) mget_block_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define mget_num_transactions_request__field_descriptors NULL
#define mget_num_transactions_request__field_indices_by_name NULL
#define mget_num_transactions_request__number_ranges NULL
const ProtobufCMessageDescriptor mget_num_transactions_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MGetNumTransactionsRequest",
  "MGetNumTransactionsRequest",
  "MGetNumTransactionsRequest",
  "",
  sizeof(MGetNumTransactionsRequest),
  0,
  mget_num_transactions_request__field_descriptors,
  mget_num_transactions_request__field_indices_by_name,
  0,  mget_num_transactions_request__number_ranges,
  (ProtobufCMessageInit) mget_num_transactions_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mget_num_transactions_response__field_descriptors[1] =
{
  {
    "num_transactions",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MGetNumTransactionsResponse, num_transactions),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mget_num_transactions_response__field_indices_by_name[] = {
  0,   /* field[0] = num_transactions */
};
static const ProtobufCIntRange mget_num_transactions_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mget_num_transactions_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MGetNumTransactionsResponse",
  "MGetNumTransactionsResponse",
  "MGetNumTransactionsResponse",
  "",
  sizeof(MGetNumTransactionsResponse),
  1,
  mget_num_transactions_response__field_descriptors,
  mget_num_transactions_response__field_indices_by_name,
  1,  mget_num_transactions_response__number_ranges,
  (ProtobufCMessageInit) mget_num_transactions_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define mget_all_transaction_ids_request__field_descriptors NULL
#define mget_all_transaction_ids_request__field_indices_by_name NULL
#define mget_all_transaction_ids_request__number_ranges NULL
const ProtobufCMessageDescriptor mget_all_transaction_ids_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MGetAllTransactionIdsRequest",
  "MGetAllTransactionIdsRequest",
  "MGetAllTransactionIdsRequest",
  "",
  sizeof(MGetAllTransactionIdsRequest),
  0,
  mget_all_transaction_ids_request__field_descriptors,
  mget_all_transaction_ids_request__field_indices_by_name,
  0,  mget_all_transaction_ids_request__number_ranges,
  (ProtobufCMessageInit) mget_all_transaction_ids_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mget_all_transaction_ids_response__field_descriptors[1] =
{
  {
    "transaction_ids",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(MGetAllTransactionIdsResponse, n_transaction_ids),
    offsetof(MGetAllTransactionIdsResponse, transaction_ids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mget_all_transaction_ids_response__field_indices_by_name[] = {
  0,   /* field[0] = transaction_ids */
};
static const ProtobufCIntRange mget_all_transaction_ids_response__number_ranges[1 + 1] =
{
  { 8, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mget_all_transaction_ids_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MGetAllTransactionIdsResponse",
  "MGetAllTransactionIdsResponse",
  "MGetAllTransactionIdsResponse",
  "",
  sizeof(MGetAllTransactionIdsResponse),
  1,
  mget_all_transaction_ids_response__field_descriptors,
  mget_all_transaction_ids_response__field_indices_by_name,
  1,  mget_all_transaction_ids_response__number_ranges,
  (ProtobufCMessageInit) mget_all_transaction_ids_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mget_transaction_request__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MGetTransactionRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mget_transaction_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange mget_transaction_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mget_transaction_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MGetTransactionRequest",
  "MGetTransactionRequest",
  "MGetTransactionRequest",
  "",
  sizeof(MGetTransactionRequest),
  1,
  mget_transaction_request__field_descriptors,
  mget_transaction_request__field_indices_by_name,
  1,  mget_transaction_request__number_ranges,
  (ProtobufCMessageInit) mget_transaction_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mget_transaction_response__field_descriptors[1] =
{
  {
    "transaction",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MGetTransactionResponse, transaction),
    &ptransaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mget_transaction_response__field_indices_by_name[] = {
  0,   /* field[0] = transaction */
};
static const ProtobufCIntRange mget_transaction_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mget_transaction_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MGetTransactionResponse",
  "MGetTransactionResponse",
  "MGetTransactionResponse",
  "",
  sizeof(MGetTransactionResponse),
  1,
  mget_transaction_response__field_descriptors,
  mget_transaction_response__field_indices_by_name,
  1,  mget_transaction_response__number_ranges,
  (ProtobufCMessageInit) mget_transaction_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
